---
- name: Download all files from an SFTP folder using ansible.posix.sftp
  hosts: localhost
  gather_facts: no
  vars:
    sftp_host: "your.sftp.server.com"  # SFTP server address
    sftp_username: "your_username"     # SFTP username
    sftp_password: "your_password"     # SFTP password (or use private_key for key-based auth)
    sftp_remote_dir: "/path/to/remote/folder"  # Remote directory to download files from
    local_download_dir: "/path/to/local/folder"  # Local directory to save files

  tasks:
    - name: Ensure local download directory exists
      ansible.builtin.file:
        path: "{{ local_download_dir }}"
        state: directory
        mode: '0755'

    - name: List files in the remote SFTP directory
      ansible.posix.sftp:
        host: "{{ sftp_host }}"
        username: "{{ sftp_username }}"
        password: "{{ sftp_password }}"  # Use `private_key` instead of `password` for key-based auth
        path: "{{ sftp_remote_dir }}"
        operation: list
      register: sftp_files

    - name: Download all files from the SFTP folder
      ansible.posix.sftp:
        host: "{{ sftp_host }}"
        username: "{{ sftp_username }}"
        password: "{{ sftp_password }}"  # Use `private_key` instead of `password` for key-based auth
        src: "{{ sftp_remote_dir }}/{{ item }}"
        dest: "{{ local_download_dir }}/{{ item }}"
        operation: get
      loop: "{{ sftp_files.files }}"
      when: item != '.' and item != '..'  # Skip special directories
